//
//
//  Generated by Agora Plastic(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : C_obj.h
//  @ Date : 2005-08-18
//  @ Author : 
//
//
#pragma once

#if !defined(_C_OBJ_H)
#define _C_OBJ_H
#include "IOClass.h"
#include <string.h>

#define MAX_NAME_SIZE 15
#define MAP_OBJ_MOVE_VELOCITY 2

class C_obj {
public:	
	C_obj(char* nam, float mas,char* sha);
	/************************************************/
	/*	nam		:	오브젝트를 구분하기 위한 이름	*/
	/*	mas		:	질량							*/
	/*	sha		:	충돌체크를 위한 모양 구분		*/
	/************************************************/
	virtual ~C_obj();

	virtual void crash_obj_move_up		( C_obj* temp );
	virtual void crash_obj_move_down	( C_obj* temp );
	virtual void crash_obj_move_left	( C_obj* temp );
	virtual void crash_obj_move_right	( C_obj* temp );

	virtual void crash_obj_fix_up		( C_obj* temp );
	virtual void crash_obj_fix_down		( C_obj* temp );
	virtual void crash_obj_fix_left		( C_obj* temp );
	virtual void crash_obj_fix_right	( C_obj* temp );

	void	setedge			(int x, int y, int width, int height);
	void	setradius		(float ra);

	char*	getshafe		(							);	
	char*	getname			(							);
	float	getmass			(							);
	void	getxy			(	int* tx, int* ty		);
	void	getvelocity		(	float* vx,  float* vy	);

	void	rename			(	char* name, char* rn	);

	void	setmass			(	float m					);
	void	setxy			(	int x,  int y			);
	void	setvelocity		(	float vx,float vy		);

	void	impulsex		(	float x					);
	void	impulsey		(	float y					);

	void	moveto			(	int x, int y			); //맵 오브젝트의 이동될 좌표
	void	step_for_fixed	(							); //맵 오브젝트의 이동 연산

	virtual	void	onDraw			(							);

	void	culision_with	(	C_obj* other_obj		);

	void	setcolision_dir (	int dir					);
	int 	getcolision_dir (							);
	

	C_obj*	next;

	int			x, y;
	int			width;
	int			height;
	int			fbefore_state;
	int			mbefore_state;

	int			repitition;
	DWORD		FastTime;
private:
	
	char		name[MAX_NAME_SIZE];
	char		shafe[MAX_NAME_SIZE];

	float		radius;			//원은 추후에 추가...
	
	//int			edge[4][2];  /*다각형의 경우: 아직 미구현*/ //꼭지점을 txt에서 읽어오는 것도 괜찮을 듯

	int			index;

	C_obj*		fixed_info;
	
	float		surface;	//표면 마찰로 쓸거	
	float		mass;		//질량

	int			colision_direction;
	
	float		velocity_x;
	float		velocity_y;

	//맵 오브젝트 일 때
	int			n_pos_x;
	int			n_pos_y;
};

#endif  //_C_OBJ_H
